# Products Clusters

In [5]:
# Import packages
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

# Autoreload
%load_ext autoreload
%autoreload 2

# Warnings
import warnings
warnings.filterwarnings('ignore')

# Import data
from bimbo.data import Bimbo

data = Bimbo().get_data()

# Load in the train and test datasets
# train_df = data['train']
# test_df = data['test']
# cliente_tabla_df = data['cliente_tabla']
producto_tabla_df = data['producto_tabla']
# town_state_df = data['town_state']
# sample_submission_df = data['sample_submission']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Memory usage of dataframe is 0.04 MB
Memory usage after optimization is: 0.11 MB
Decreased by -184.7%
Memory usage of dataframe is 14.27 MB
Memory usage after optimization is: 19.51 MB
Decreased by -36.7%
Memory usage of dataframe is 373.80 MB
Memory usage after optimization is: 120.15 MB
Decreased by 67.9%
Memory usage of dataframe is 0.02 MB
Memory usage after optimization is: 0.02 MB
Decreased by 6.0%
Memory usage of dataframe is 6225.47 MB
Memory usage after optimization is: 2122.32 MB
Decreased by 65.9%
Memory usage of dataframe is 106.80 MB
Memory usage after optimization is: 33.38 MB
Decreased by 68.7%


In [6]:
producto_tabla_df.head(3)

Producto_ID                          NombreProducto
0            0                       NO IDENTIFICADO 0
1            9               Capuccino Moka 750g NES 9
2           41  Bimbollos Ext sAjonjoli 6p 480g BIM 41

### Text pre-processing

In [9]:
from bimbo.text_preprocess import Preprocess

In [10]:
text = "Capuccino Moka 750g NES 9"

In [11]:
pr = Preprocess()

In [16]:
lower_text = pr.to_lower(text)
sentence_tokens = pr.sentence_tokenize(lower_text)
for each_sent in sentence_tokens:
    lemmatizzed_sent = pr.lemmatize(each_sent)
    clean_text = pr.remove_numbers(lemmatizzed_sent)
    clean_text = pr.remove_punct(clean_text)
    clean_text = pr.remove_Tags(clean_text)
    clean_text = pr.remove_stopwords(clean_text)
    word_tokens = pr.word_tokenize(clean_text)
    print(word_tokens)

['capuccino', 'moka', 'g', 'ne']


In [14]:
print(producto_tabla_df['NombreProducto'])

0                                    NO IDENTIFICADO 0
1                            Capuccino Moka 750g NES 9
2               Bimbollos Ext sAjonjoli 6p 480g BIM 41
3                       Burritos Sincro 170g CU LON 53
4                  Div Tira Mini Doradita 4p 45g TR 72
5                    Pan Multigrano Linaza 540g BIM 73
6                         Tostado Integral 180g WON 98
7                               Pan Blanco 567g WON 99
8               Super Pan Bco Ajonjoli 680g SP WON 100
9                   Wonder 100pct mediano 475g WON 106
10                   Wonder 100pct gde 680g SP WON 107
11                 Baguette Precocida Cong 280g DH 108
12                        Pan Multicereal 475g WON 109
13                       Tostado Integral 180g WON 112
14            Biscotel Receta Original 410g CU SUA 122
15                    Super Bollos 5in 8p 540g WON 123
16                              Bollos 8p 450g WON 125
17                      Bollos BK 4in 36p 1635g SL 131
18        

In [15]:
# Found on Kaggle (https://www.kaggle.com/vykhand/exploring-products)
# Credit: Andrey Vykhodtsev

producto_tabla_df['short_name'] = producto_tabla_df.NombreProducto.str.extract('^(\D*)', expand=False)
producto_tabla_df['brand'] = producto_tabla_df.NombreProducto.str.extract('^.+\s(\D+) \d+$', expand=False)
w = producto_tabla_df.NombreProducto.str.extract('(\d+)(Kg|g)', expand=True)
producto_tabla_df['weight'] = w[0].astype('float')*w[1].map({'Kg':1000, 'g':1})
producto_tabla_df['pieces'] =  producto_tabla_df.NombreProducto.str.extract('(\d+)p ', expand=False).astype('float')
producto_tabla_df.head()

Producto_ID                          NombreProducto  \
0            0                       NO IDENTIFICADO 0   
1            9               Capuccino Moka 750g NES 9   
2           41  Bimbollos Ext sAjonjoli 6p 480g BIM 41   
3           53          Burritos Sincro 170g CU LON 53   
4           72     Div Tira Mini Doradita 4p 45g TR 72   

                 short_name         brand  weight  pieces  
0          NO IDENTIFICADO   IDENTIFICADO     NaN     NaN  
1           Capuccino Moka            NES   750.0     NaN  
2  Bimbollos Ext sAjonjoli            BIM   480.0     6.0  
3          Burritos Sincro            LON   170.0     NaN  
4   Div Tira Mini Doradita             TR    45.0     4.0

The **short_name** and the **brand** are important.

In [17]:
producto_tabla_df["ProcessedText"] = producto_tabla_df.short_name.apply(lambda x : pr.preprocess(x))
producto_tabla_df["ProcessedText"]

0                       [identificado]
1                    [capuccino, moka]
2          [bimbollos, ext, sajonjoli]
3                    [burrito, sincro]
4          [div, tira, mini, doradita]
5            [pan, multigrano, linaza]
6                  [tostado, integral]
7                        [pan, blanco]
8          [super, pan, bco, ajonjoli]
9                             [wonder]
10                            [wonder]
11         [baguette, precocida, cong]
12                  [pan, multicereal]
13                 [tostado, integral]
14        [biscotel, receta, original]
15                     [super, bollos]
16                            [bollos]
17                        [bollos, bk]
18                        [bollos, bk]
19                        [bollos, bk]
20                        [bollos, bk]
21                          [hot, dog]
22                   [super, hot, dog]
23                    [medias, noches]
24                         [bollo, wb]
25                     [m

In [18]:
# # SHOULD I ADD MORE STOP WORDS ???? (and take them away ????)
# stop = ['g','p','won','mla','bim','lon','cc', 'ml', 'dh', 'sl', 'ne', 'bk', 'in', 'tir', 'mta', 'tr', 'kg']

# producto_tabla_df["ProcessedText"] = producto_tabla_df["ProcessedText"]\
#                                     .apply(lambda x: [item for item in x if item not in stop])
# producto_tabla_df["ProcessedText"]

### product clustering

In [19]:
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing import sequence

vocab_size = 10000 # maximum number of words to keep (keeps the most frequent)
maxlen = 200 # maximum number of words in a review

Using TensorFlow backend.


In [20]:
tokenizer = Tokenizer(num_words=maxlen)
tokenizer.fit_on_texts(list(producto_tabla_df["ProcessedText"].values))
X_train = tokenizer.texts_to_sequences(producto_tabla_df["ProcessedText"] .values)
x_train = sequence.pad_sequences(X_train, maxlen = maxlen)

In [21]:
x_train

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,  31],
       ...,
       [  0,   0,   0, ...,   0,  25, 145],
       [  0,   0,   0, ...,   0,  25, 145],
       [  0,   0,   0, ...,   0,  25, 145]], dtype=int32)

In [22]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=42)
kmeans.fit(x_train)
y_kmeans = kmeans.predict(x_train)

In [23]:
y_kmeans

array([ 0,  0, 11, ...,  2,  2,  2], dtype=int32)

In [24]:
np.unique(y_kmeans)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41], dtype=int32)

In [25]:
cluster_df = pd.DataFrame(y_kmeans, columns=['cluster'])
cluster_df.head(3)

cluster
0        0
1        0
2       11

In [26]:
producto_clusters_df = pd.concat([producto_tabla_df, cluster_df + 1], axis=1)
producto_clusters_df

Producto_ID                                  NombreProducto  \
0               0                               NO IDENTIFICADO 0   
1               9                       Capuccino Moka 750g NES 9   
2              41          Bimbollos Ext sAjonjoli 6p 480g BIM 41   
3              53                  Burritos Sincro 170g CU LON 53   
4              72             Div Tira Mini Doradita 4p 45g TR 72   
5              73               Pan Multigrano Linaza 540g BIM 73   
6              98                    Tostado Integral 180g WON 98   
7              99                          Pan Blanco 567g WON 99   
8             100          Super Pan Bco Ajonjoli 680g SP WON 100   
9             106              Wonder 100pct mediano 475g WON 106   
10            107               Wonder 100pct gde 680g SP WON 107   
11            108             Baguette Precocida Cong 280g DH 108   
12            109                    Pan Multicereal 475g WON 109   
13            112                   Tostado Integral 180g WON 112   
14            122        Biscotel Receta Original 410g CU SUA 122   
15            123                Super Bollos 5in 8p 540g WON 123   
16            125                          Bollos 8p 450g WON 125   
17            131                  Bollos BK 4in 36p 1635g SL 131   
18            132                  Bollos BK 5in 30p 1730g SL 132   
19            134              Bollos BK 4in 30p 1635g TIR SL 134   
20            135              Bollos BK 5in 20p 1730g TIR SL 135   
21            141                        Hot Dogs 8p 290g WON 141   
22            145                  Super Hot Dogs 8p 435g WON 145   
23            151                Medias Noches 24p 470g BK SL 151   
24            157             Bollo WB 5in snAjn 20p 1950g SL 157   
25            160                       Molido Bolsa 180g WON 160   
26            161                Bollos KFC 5in 15p 1237g WON 161   
27            162                             Molido 25Kg WON 162   
28            163                              Molido 5Kg WON 163   
29            179      Tostado Int 0pct Grasa Azucar 200g WON 179   
...           ...                                             ...   
2562        49737                   Powerade Limon 600ml CC 49737   
2563        49738                    Powerade Mora 600ml CC 49738   
2564        49739                 Powerade Naranja 600ml CC 49739   
2565        49740                     Powerade Uva 600ml CC 49740   
2566        49754                  Totopos Redondos 250g DH 49754   
2567        49765                       Fanta Lata 355ml CC 49765   
2568        49766                 Sprite Zero Lata 355ml CC 49766   
2569        49769               Sidral Mundet Lata 355ml CC 49769   
2570        49773         Bombonete San Valentin 3p 55g MLA 49773   
2571        49779            Tortillinas 22p 570g NW MTA TR 49779   
2572        49781          Tortillinas 12p 310g Prom MTA TR 49781   
2573        49782            Tortillinas 12p 310g NW MTA TR 49782   
2574        49810            Totopo Chilaquiles 500g TAB MR 49810   
2575        49835            Bimkingo Clasico Prom 135g LON 49835   
2576        49860                Gansito ME 5p 250g MTA MLA 49860   
2577        49892     Wonder 100pct mediano 475g NM MTA WON 49892   
2578        49920               Conchas 3p 180g Prom TAB TR 49920   
2579        49928                      Dona 1p 26g Tira BIM 49928   
2580        49944    Pan Blanco Bimbo Rendidor 567g TNB BIM 49944   
2581        49972    Pan Blanco Bimbo Rendidor 567g MTA BIM 49972   
2582        49973        Pan Blanco Bimbo Rendidor 567g BIM 49973   
2583        49986                   Tostado Blanco 180g WON 49986   
2584        49988               Tostado Blanco 180g MTA WON 49988   
2585        49989               Tostado Blanco 180g TAB WON 49989   
2586        49990                 Tostado Integral 180g WON 49990   
2587        49992             Tostado Integral 180g MTA WON 49992   
2588

### Write CSV

In [18]:
producto_clusters_df.to_csv('../data/producto_clusters.csv',index=False)